bert_config: './fashion_annotation/bert_config.json'
tokenizer_config: './fashion_annotation'

image_res: 256
batch_size_train: 16
batch_size_test: 256

queue_size: 65536
# queue_size: 8192
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 256

alpha: 0.4
distill: True
warm_up: True

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.2} # 0.02
schedular: {sched: cosine, lr: 2e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}