bert_config: './fashion_annotation/config_bert.json'
tokenizer_config: './fashion_annotation'

image_res: 256
batch_size_train: 16
batch_size_test: 256

queue_size: 65536
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07

alpha: 0.4
warm_up: True

optimizer: {opt: adamW, lr: 6e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 6e-5, epochs: 30, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}